# Capacidades estratégicas y de defensa (curado).
# IMPORTANTE: los inventarios curados son órdenes de magnitud de fuentes abiertas, NO cifras de The Military Balance.
# Cada fila indica fecha de referencia, definición y fiabilidad. Las series cuantitativas de gasto y personal
# provienen de SIPRI (vía WDI) y Correlates of War NMC.

# country_id, status, first_test_date, first_test_name, warheads_jan2024, warheads_jan2025, npt_status, doctrine_note, verification_status, source_ids, certainty
NUCLEAR = [
 ("USA","estado_nuclear_TNP","1945-07-16","Trinity",5328,5177,"parte (EEN reconocido)","Disuasión extendida a aliados; Nuclear Posture Review 2022 (no se descarta primer uso en circunstancias extremas)","VERIF_SESION","SRC_SIPRI_YB2025_NUC;SRC_HIROSHIMA_NUC","Alta"),
 ("RUS","estado_nuclear_TNP","1949-08-29","RDS-1",5580,5459,"parte (EEN reconocido; continuador de la URSS)","Doctrina revisada en noviembre de 2024: amplía supuestos de uso (ataque de Estado no nuclear apoyado por potencia nuclear)","VERIF_SESION","SRC_SIPRI_YB2025_NUC;SRC_HIROSHIMA_NUC","Alta"),
 ("GBR","estado_nuclear_TNP","1952-10-03","Hurricane",225,225,"parte (EEN reconocido)","Disuasión mínima basada en SSBN (Trident); techo de arsenal elevado a 260 (2021)","VERIF_SESION","SRC_SIPRI_YB2025_NUC;SRC_HIROSHIMA_NUC","Alta"),
 ("FRA","estado_nuclear_TNP","1960-02-13","Gerboise Bleue",290,290,"parte (EEN reconocido)","Disuasión estrictamente defensiva de 'intereses vitales'; componentes aéreo y naval","VERIF_SESION","SRC_SIPRI_YB2025_NUC;SRC_HIROSHIMA_NUC","Alta"),
 ("CHN","estado_nuclear_TNP","1964-10-16","Proyecto 596",500,600,"parte (EEN reconocido)","Política declarada de no primer uso; expansión rápida (~100 ojivas/año desde 2023 según SIPRI)","VERIF_SESION","SRC_SIPRI_YB2025_NUC;SRC_HIROSHIMA_NUC","Alta"),
 ("IND","estado_nuclear_fuera_TNP","1974-05-18","Smiling Buddha (Pokhran-I)",172,180,"no parte","No primer uso con represalia masiva; tríada en desarrollo","VERIF_SESION","SRC_SIPRI_YB2025_NUC;SRC_HIROSHIMA_NUC","Alta"),
 ("PAK","estado_nuclear_fuera_TNP","1998-05-28","Chagai-I",170,170,"no parte","Disuasión de espectro completo; armas tácticas (Nasr); primer uso no descartado","VERIF_SESION","SRC_SIPRI_YB2025_NUC;SRC_HIROSHIMA_NUC","Alta"),
 ("ISR","estado_nuclear_no_declarado","","(sin prueba reconocida)",90,90,"no parte","Opacidad nuclear (amimut)","VERIF_SESION","SRC_SIPRI_YB2025_NUC;SRC_HIROSHIMA_NUC","Media"),
 ("PRK","estado_nuclear_fuera_TNP","2006-10-09","Primera prueba subterránea",50,50,"retirada anunciada en 2003","Ley de 2022 sobre política nuclear (uso preventivo); material fisible para hasta ~40 ojivas más (SIPRI)","VERIF_SESION","SRC_SIPRI_YB2025_NUC;SRC_HIROSHIMA_NUC","Media"),
 ("ZAF","programa_desmantelado","","(sin prueba confirmada)",0,0,"parte desde 1991","Construyó 6 dispositivos y los desmanteló (1989-1991)","CONOC_EXPERTO","SRC_NTI","Alta"),
 ("UKR","arsenal_heredado_transferido","","",0,0,"parte desde 1994","Heredó ~1.900 ojivas estratégicas soviéticas; transferidas a Rusia (Memorando de Budapest)","CONOC_EXPERTO","SRC_NTI","Alta"),
 ("KAZ","arsenal_heredado_transferido","","",0,0,"parte","Arsenal soviético transferido a Rusia (1995)","CONOC_EXPERTO","SRC_NTI","Alta"),
 ("BLR","arsenal_heredado_transferido_y_despliegue_ruso","","",0,0,"parte","Armas soviéticas transferidas (1996); Rusia anunció despliegue de armas nucleares tácticas en su territorio (2023)","CONOC_EXPERTO","SRC_NTI","Media"),
 ("IRN","programa_umbral","","",0,0,"parte (amenaza de retirada)","Uranio enriquecido al 60% acumulado (OIEA, 2024-2025); instalaciones atacadas en junio de 2025","CONOC_EXPERTO","SRC_NTI","Media"),
 ("IRQ","programa_desmantelado","","",0,0,"parte","Programa destruido tras 1991 (UNSCOM); Osirak bombardeado en 1981","CONOC_EXPERTO","SRC_NTI","Alta"),
 ("LBY","programa_desmantelado","","",0,0,"parte","Renuncia en diciembre de 2003","CONOC_EXPERTO","SRC_NTI","Alta"),
 ("SYR","programa_destruido","","",0,0,"parte","Reactor de Al Kibar destruido por Israel (2007)","CONOC_EXPERTO","SRC_NTI","Media"),
 ("BRA","programa_abandonado","","",0,0,"parte desde 1998","Programa paralelo militar abandonado; submarino de propulsión nuclear en desarrollo","CONOC_EXPERTO","SRC_NTI","Media"),
 ("ARG","programa_abandonado","","",0,0,"parte desde 1995","Acuerdo ABACC con Brasil (1991)","CONOC_EXPERTO","SRC_NTI","Media"),
 ("KOR","programa_abandonado","","",0,0,"parte","Programa clandestino abandonado en los años 70 bajo presión de EE.UU.","CONOC_EXPERTO","SRC_NTI","Media"),
 ("TWN","programa_abandonado","","",0,0,"no reconocido como Estado parte","Programa desmantelado en 1988 bajo presión de EE.UU.","CONOC_EXPERTO","SRC_NTI","Media"),
]

# inv_id, country_id, category, item_definition, value_low, value_high, ref_date, status_note, verification_status, certainty, source_ids
STRATEGIC_INVENTORY = [
 ("INV001","USA","portaaviones","Portaaviones de propulsión nuclear en servicio (clases Nimitz y Ford)",11,11,"2025","Exigencia legal de mantener 11","CONOC_EXPERTO","Alta","SRC_IISS_MB"),
 ("INV002","CHN","portaaviones","Portaaviones (Liaoning, Shandong, Fujian)",2,3,"2025","Fujian en pruebas/entrada en servicio en 2025","CONOC_EXPERTO","Media","SRC_IISS_MB"),
 ("INV003","GBR","portaaviones","Portaaviones clase Queen Elizabeth",2,2,"2025","","CONOC_EXPERTO","Alta","SRC_IISS_MB"),
 ("INV004","FRA","portaaviones","Portaaviones nuclear Charles de Gaulle",1,1,"2025","Sucesor (PANG) previsto ~2038","CONOC_EXPERTO","Alta","SRC_IISS_MB"),
 ("INV005","IND","portaaviones","INS Vikramaditya, INS Vikrant",2,2,"2025","","CONOC_EXPERTO","Alta","SRC_IISS_MB"),
 ("INV006","RUS","portaaviones","Almirante Kuznetsov",0,1,"2025","En reparación prolongada desde 2017; disponibilidad operativa nula o muy baja","CONOC_EXPERTO","Media","SRC_IISS_MB"),
 ("INV007","ITA","portaaviones","Portaaviones ligero Cavour (F-35B)",1,2,"2025","Garibaldi en proceso de baja","CONOC_EXPERTO","Media","SRC_IISS_MB"),
 ("INV008","USA","SSBN","Submarinos de misiles balísticos (clase Ohio)",14,14,"2025","Sustitución por clase Columbia (primer buque ~2028-2030)","CONOC_EXPERTO","Alta","SRC_IISS_MB;SRC_FAS_NUC"),
 ("INV009","RUS","SSBN","Submarinos de misiles balísticos (Borei/Borei-A, Delta IV)",10,13,"2025","","CONOC_EXPERTO","Media","SRC_IISS_MB;SRC_FAS_NUC"),
 ("INV010","CHN","SSBN","Submarinos de misiles balísticos (Tipo 094/094A)",6,6,"2025","","CONOC_EXPERTO","Media","SRC_IISS_MB;SRC_FAS_NUC"),
 ("INV011","GBR","SSBN","Clase Vanguard",4,4,"2025","Sustitución por clase Dreadnought (2030s)","CONOC_EXPERTO","Alta","SRC_IISS_MB"),
 ("INV012","FRA","SSBN","Clase Triomphant",4,4,"2025","","CONOC_EXPERTO","Alta","SRC_IISS_MB"),
 ("INV013","IND","SSBN","Clase Arihant",2,3,"2025","INS Arighaat en servicio en 2024","CONOC_EXPERTO","Media","SRC_IISS_MB"),
 ("INV014","USA","bombarderos_estrategicos","B-52H, B-1B, B-2A (B-21 en producción)",140,160,"2025","","CONOC_EXPERTO","Media","SRC_IISS_MB"),
 ("INV015","RUS","bombarderos_estrategicos","Tu-95MS, Tu-160, Tu-22M3",100,130,"2025","Pérdidas por ataques ucranianos con drones (Operación 'Telaraña', 01-06-2025) no cuantificadas con precisión","CONOC_EXPERTO","Baja","SRC_IISS_MB"),
 ("INV016","USA","aviones_combate_5a_gen","F-22 + F-35 (todas las ramas)",500,800,"2025","","CONOC_EXPERTO","Baja","SRC_IISS_MB"),
 ("INV017","CHN","aviones_combate_5a_gen","J-20",200,300,"2025","Estimaciones abiertas muy divergentes","CONOC_EXPERTO","Baja","SRC_IISS_MB"),
 ("INV018","RUS","carros_combate_activos","Carros de combate en unidades activas",None,None,"2025","Pérdidas masivas en Ucrania (miles documentadas visualmente por Oryx); stock depende de reactivación desde almacenes","CONOC_EXPERTO","Baja","SRC_IISS_MB"),
 ("INV019","USA","bases_extranjeras","Instalaciones militares en el extranjero",700,800,"2021","Cifras según la definición de 'base' (estudios académicos)","CONOC_EXPERTO","Baja","SRC_IISS_MB"),
 ("INV020","RUS","bases_extranjeras","Bases y despliegues permanentes fuera del territorio (Armenia, Bielorrusia, Tayikistán, Kirguistán, Transnistria, Abjasia, Osetia del Sur; Siria hasta 2024-2025)",8,12,"2025","Futuro de Tartús y Hmeimim incierto tras la caída de Assad","CONOC_EXPERTO","Media","SRC_IISS_MB"),
 ("INV021","CHN","bases_extranjeras","Base de apoyo en Yibuti (desde 2017); base de Ream (Camboya) con presencia reportada",1,2,"2025","","CONOC_EXPERTO","Media","SRC_IISS_MB"),
 ("INV022","USA","satelites_militares","Constelaciones de alerta temprana, navegación (GPS), comunicaciones e inteligencia",None,None,"2025","Recuento no verificado; ver UCS Satellite Database","CONOC_EXPERTO","Baja","SRC_IISS_MB"),
]

# country_id, conscription_status, since, notes, certainty
CONSCRIPTION = [
 ("USA","voluntario","1973","Registro obligatorio (Selective Service) para varones","Alta"),
 ("GBR","voluntario","1960","Fin del National Service (últimos llamados 1960, últimos licenciados 1963)","Alta"),
 ("FRA","voluntario","1997","Servicio suspendido (Ley 1997); Servicio Nacional Universal civil","Alta"),
 ("DEU","voluntario","2011","Suspendido en 2011; ley de nuevo servicio militar (con registro obligatorio) aprobada/en trámite en 2025","Media"),
 ("ESP","voluntario","2001","Suspensión del servicio militar obligatorio","Alta"),
 ("ITA","voluntario","2005","","Alta"),
 ("POL","voluntario","2009","Programas de formación voluntaria ampliados desde 2022","Alta"),
 ("NLD","voluntario","1996","Suspendido","Alta"),
 ("BEL","voluntario","1994","","Alta"),
 ("SWE","obligatorio_selectivo","2018","Reactivado tras suspensión (2010); incluye mujeres","Alta"),
 ("NOR","obligatorio_selectivo","","Universal para ambos sexos desde 2015","Alta"),
 ("DNK","obligatorio_selectivo","","Ampliación a mujeres desde 2025-2026","Media"),
 ("FIN","obligatorio","","Reserva en tiempo de guerra ~280.000","Alta"),
 ("EST","obligatorio","","","Alta"),
 ("LVA","obligatorio","2023","Reinstaurado","Alta"),
 ("LTU","obligatorio","2015","Reinstaurado","Alta"),
 ("GRC","obligatorio","","","Alta"),
 ("TUR","obligatorio","","Con opción de pago para reducir el servicio","Alta"),
 ("CHE","obligatorio","","Ejército de milicia","Alta"),
 ("AUT","obligatorio","","Referéndum 2013 mantuvo el servicio","Alta"),
 ("ISR","obligatorio","","Ambos sexos; controversia sobre exención de ultraortodoxos (fallo del Tribunal Supremo 2024)","Alta"),
 ("RUS","obligatorio","","12 meses; movilización parcial en septiembre de 2022","Alta"),
 ("UKR","movilizacion_general","2022","Ley marcial; edad de movilización reducida a 25 años (2024)","Alta"),
 ("KOR","obligatorio","","18-21 meses","Alta"),
 ("PRK","obligatorio","","Servicio muy prolongado (en torno a 10 años para varones; fuentes abiertas)","Media"),
 ("TWN","obligatorio","2024","Restablecido el servicio de 1 año","Alta"),
 ("CHN","obligatorio_legal_voluntario_en_practica","","Cuotas cubiertas con voluntarios","Media"),
 ("VNM","obligatorio","","","Media"),
 ("SGP","obligatorio","","National Service de 2 años","Alta"),
 ("THA","loteria","","","Media"),
 ("IRN","obligatorio","","","Alta"),
 ("EGY","obligatorio","","","Alta"),
 ("MAR","obligatorio","2019","Reinstaurado","Media"),
 ("DZA","obligatorio","","","Media"),
 ("BRA","obligatorio_legal_voluntario_en_practica","","Alistamiento obligatorio; mayoría de plazas cubiertas con voluntarios","Media"),
 ("ARG","voluntario","1994","Abolido tras el caso Carrasco","Alta"),
 ("CHL","obligatorio_legal_voluntario_en_practica","2005","Sorteo solo si no se cubren las plazas voluntarias","Media"),
 ("COL","obligatorio","","Con exenciones","Media"),
 ("MEX","obligatorio_nominal","","Servicio Militar Nacional (sorteo)","Media"),
 ("VEN","obligatorio_nominal","","","Baja"),
 ("CUB","obligatorio","","","Media"),
 ("IND","voluntario","","Esquema Agnipath (2022) de servicio de 4 años","Alta"),
 ("PAK","voluntario","","","Alta"),
 ("JPN","voluntario","","","Alta"),
 ("AUS","voluntario","1972","","Alta"),
 ("CAN","voluntario","","","Alta"),
]

# company_id, name, country_id, ownership, sector, main_products, founded, notes, certainty
DEFENSE_COMPANIES = [
 ("DC001","Lockheed Martin","USA","privada_cotizada","aeroespacial_defensa","F-35, F-16, misiles PAC-3, satélites","1995 (fusión)","Mayor empresa de armamento del mundo por ventas según SIPRI Top 100 (varios años)","Alta"),
 ("DC002","RTX (Raytheon Technologies)","USA","privada_cotizada","misiles_sensores_motores","Patriot, AMRAAM, Tomahawk, motores Pratt & Whitney","2020 (fusión)","","Alta"),
 ("DC003","Northrop Grumman","USA","privada_cotizada","aeroespacial_defensa","B-21, sistemas espaciales, ICBM Sentinel","1994 (fusión)","","Alta"),
 ("DC004","General Dynamics","USA","privada_cotizada","terrestre_naval","Abrams, submarinos (Electric Boat), Gulfstream","1952","","Alta"),
 ("DC005","Boeing (Defense, Space & Security)","USA","privada_cotizada","aeroespacial","F-15EX, KC-46, AH-64, P-8","1916","","Alta"),
 ("DC006","BAE Systems","GBR","privada_cotizada","multidominio","Typhoon (socio), submarinos Astute/Dreadnought, vehículos Bradley/CV90","1999","Gran presencia en EE.UU.","Alta"),
 ("DC007","Rostec","RUS","estatal","conglomerado_defensa","Sukhoi, Kalashnikov, Uralvagonzavod, sistemas S-400 (vía Almaz-Antey es otra empresa)","2007","Sancionada","Alta"),
 ("DC008","Almaz-Antey","RUS","estatal","defensa_aerea","S-300/S-400/S-500","2002","","Alta"),
 ("DC009","United Shipbuilding Corporation","RUS","estatal","naval","Submarinos y buques de superficie","2007","","Alta"),
 ("DC010","AVIC (Aviation Industry Corporation of China)","CHN","estatal","aeroespacial","J-20, J-10, Y-20, drones Wing Loong","2008 (reunificación)","","Alta"),
 ("DC011","NORINCO (China North Industries Group)","CHN","estatal","terrestre","Carros, artillería, munición","1980","","Alta"),
 ("DC012","CSSC (China State Shipbuilding Corporation)","CHN","estatal","naval","Portaaviones, destructores Tipo 055","2019 (fusión)","","Alta"),
 ("DC013","CASC / CASIC","CHN","estatal","misiles_espacio","Misiles balísticos y de crucero, lanzadores Long March","1999","","Alta"),
 ("DC014","Airbus (Defence and Space)","FRA;DEU;ESP","privada_cotizada_con_participacion_estatal","aeroespacial","A400M, Eurofighter (socio), satélites","2000","","Alta"),
 ("DC015","Thales","FRA","mixta (Estado francés ~26%)","electronica_defensa","Radares, sistemas de misiles, comunicaciones","2000 (antigua Thomson-CSF)","","Alta"),
 ("DC016","Dassault Aviation","FRA","privada (Grupo Dassault) con participación de Airbus","aeroespacial","Rafale, Falcon","1929","","Alta"),
 ("DC017","Naval Group","FRA","estatal_mayoritaria","naval","Submarinos Barracuda, fragatas FREMM/FDI","1631 (arsenales)","","Alta"),
 ("DC018","MBDA","FRA;GBR;ITA","conjunta (Airbus, BAE, Leonardo)","misiles","Meteor, Storm Shadow/SCALP, Aster","2001","","Alta"),
 ("DC019","Leonardo","ITA","mixta (Estado ~30%)","aeroespacial_electronica","Helicópteros AW, electrónica, socio Eurofighter","1948 (Finmeccanica)","","Alta"),
 ("DC020","Rheinmetall","DEU","privada_cotizada","terrestre_municion","Munición de 155 mm, cañón del Leopard 2, Lynx","1889","Expansión fuerte tras 2022","Alta"),
 ("DC021","KNDS (Krauss-Maffei Wegmann + Nexter)","DEU;FRA","privada","terrestre","Leopard 2, CAESAR, Leclerc","2015","","Alta"),
 ("DC022","Saab","SWE","privada_cotizada","multidominio","Gripen, GlobalEye, Carl-Gustaf, NLAW (con Thales)","1937","","Alta"),
 ("DC023","Hanwha Aerospace","KOR","privada (chaebol)","terrestre_aeroespacial","K9 Thunder, K239 Chunmoo","1977","Grandes contratos con Polonia (2022)","Alta"),
 ("DC024","Hyundai Rotem","KOR","privada","terrestre","K2 Black Panther","1999","","Alta"),
 ("DC025","Korea Aerospace Industries","KOR","privada_cotizada","aeroespacial","KF-21, FA-50","1999","","Alta"),
 ("DC026","Mitsubishi Heavy Industries","JPN","privada_cotizada","multidominio","Submarinos, misiles, F-2; socio del GCAP","1884","","Alta"),
 ("DC027","Hindustan Aeronautics Limited","IND","estatal","aeroespacial","Tejas, helicópteros, Su-30MKI bajo licencia","1940","","Alta"),
 ("DC028","Bharat Electronics","IND","estatal","electronica","Radares, sistemas de defensa aérea","1954","","Alta"),
 ("DC029","Elbit Systems","ISR","privada_cotizada","electronica_drones","Drones Hermes, artillería, sistemas C4I","1966","","Alta"),
 ("DC030","Rafael Advanced Defense Systems","ISR","estatal","misiles_defensa_aerea","Cúpula de Hierro, David's Sling, Spike","1948","","Alta"),
 ("DC031","Israel Aerospace Industries","ISR","estatal","aeroespacial","Arrow, drones Heron, satélites","1953","","Alta"),
 ("DC032","Baykar","TUR","privada_familiar","drones","Bayraktar TB2, Akıncı, Kızılelma","1984","Papel destacado en Nagorno Karabaj 2020 y Ucrania 2022","Alta"),
 ("DC033","Aselsan","TUR","estatal_mayoritaria (Fundación de las FF.AA.)","electronica","Radares, comunicaciones, defensa aérea","1975","","Alta"),
 ("DC034","Embraer (Defesa & Segurança)","BRA","privada_cotizada_con_accion_de_oro","aeroespacial","KC-390, Super Tucano","1969","Privatizada en 1994","Alta"),
 ("DC035","Fabricaciones Militares / FAdeA","ARG","estatal","terrestre_aeronautica","Municiones; aviones de entrenamiento Pampa","1941 / 1927","","Media"),
 ("DC036","Navantia","ESP","estatal (SEPI)","naval","Fragatas F-110, submarinos S-80","2005","","Alta"),
 ("DC037","Indra","ESP","mixta (SEPI ~28%)","electronica","Radares, simulación, socio FCAS","1993","","Alta"),
 ("DC038","Iran Aircraft Manufacturing / HESA y Shahed Aviation Industries","IRN","estatal_CGRI","drones","Shahed-136 (exportado a Rusia, producido localmente como Geran-2)","1976","","Media"),
 ("DC039","Ukroboronprom (UDI)","UKR","estatal","conglomerado","Neptune, blindados, producción de drones","2010","Reorganizado como Ukrainian Defense Industry","Media"),
 ("DC040","EDGE Group","ARE","estatal","conglomerado","Misiles, drones, municiones","2019","","Media"),
]

# program_id, country_ids, name, type, start, status, description, certainty
PROGRAMS = [
 ("DP001","USA;GBR;ITA;NLD;AUS;NOR;DNK;CAN;TUR","Programa F-35 Joint Strike Fighter","avion_combate","2001","en_produccion","Turquía expulsada del programa (2019) por la compra del S-400 ruso.","Alta"),
 ("DP002","FRA;DEU;ESP","FCAS/SCAF","avion_combate_6a_gen","2017","en_desarrollo_con_tensiones","Futuro sistema aéreo de combate franco-germano-español.","Alta"),
 ("DP003","GBR;ITA;JPN","GCAP (Tempest)","avion_combate_6a_gen","2022","en_desarrollo","","Alta"),
 ("DP004","AUS;GBR;USA","AUKUS Pilar I","submarino_nuclear","2021","en_desarrollo","Australia adquirirá submarinos Virginia y luego SSN-AUKUS.","Alta"),
 ("DP005","USA","Sentinel (LGM-35A)","ICBM","2020","en_desarrollo_sobrecostes","Sustituto del Minuteman III; incumplimiento Nunn-McCurdy (2024).","Alta"),
 ("DP006","USA","Golden Dome","defensa_antimisiles","2025","anunciado","Escudo antimisiles anunciado en 2025.","Media"),
 ("DP007","EUU","Iniciativa Europea de Munición / ASAP y SAFE","produccion_municion","2023","en_ejecucion","Producción de munición de 155 mm para Ucrania; préstamos SAFE de 150.000 M EUR (2025).","Media"),
 ("DP008","POL","Programa de modernización polaco","adquisiciones","2022","en_ejecucion","Compras de K2, K9, Abrams, HIMARS, Apache; objetivo de gasto en defensa >4% del PIB.","Alta"),
 ("DP009","TUR","TF-X/KAAN","avion_combate_5a_gen","2016","en_desarrollo","Primer vuelo en 2024.","Alta"),
 ("DP010","IND","Proyecto 75I y AMCA","submarinos/avion_5a_gen","2010s","en_desarrollo","","Media"),
 ("DP011","CHN","Modernización de la Armada del EPL","naval","2000s","en_ejecucion","Mayor armada del mundo por número de buques (estimaciones del DoD de EE.UU.).","Media"),
 ("DP012","DEU","Fondo especial de 100.000 M EUR (Sondervermögen Bundeswehr)","financiacion","2022","en_ejecucion","'Zeitenwende'.","Alta"),
 ("DP013","ORG_NATO","Objetivo de gasto 5% del PIB (3,5% defensa básica + 1,5% relacionado) para 2035","compromiso_gasto","2025-06-25","acordado","Cumbre de La Haya; España obtuvo una flexibilidad.","Media"),
 ("DP014","ORG_NATO","Objetivo de gasto 2% del PIB","compromiso_gasto","2014-09-05","acordado","Cumbre de Gales.","Alta"),
]
