# Empresas estratégicas, reservas energéticas y minerales críticos (curado). CONOC_EXPERTO.
# Los rankings y cifras corporativas cambian cada año: no extrapolar a otras fechas.

# company_id, name, country_id, sector, ownership_current, founded, ownership_events, strategic_role, certainty
COMPANIES = [
 ("CO001","Saudi Aramco","SAU","petroleo_gas","estatal (salida a bolsa parcial ~1,5% en 2019)","1933 (CASOC)","Participación estatal gradual 1973-1980; nacionalización total 1980; OPV 2019","Mayor productor de crudo del mundo; capacidad de reserva clave para el mercado","Alta"),
 ("CO002","PDVSA","VEN","petroleo_gas","estatal","1976-01-01","Nacionalización petrolera 1976; despidos masivos tras paro 2002-2003; sanciones EE.UU. 2019","Principal fuente de divisas de Venezuela","Alta"),
 ("CO003","Pemex","MEX","petroleo_gas","estatal","1938-06-07","Expropiación petrolera de Cárdenas (18-03-1938); apertura parcial 2013-2014 revertida en parte","Empresa petrolera más endeudada del mundo (estimaciones de mercado)","Alta"),
 ("CO004","Petrobras","BRA","petroleo_gas","mixta (control estatal)","1953-10-03","Monopolio hasta 1997; escándalo Lava Jato (2014-)","Presal (descubierto 2006)","Alta"),
 ("CO005","YPF","ARG","petroleo_gas","mixta (51% estatal desde 2012)","1922-06-03","Privatizada 1993 (Repsol 1999); expropiación del 51% (2012); fallo judicial en Nueva York (2023) de ~16.000 M USD contra Argentina","Vaca Muerta","Alta"),
 ("CO006","Gazprom","RUS","gas","estatal_mayoritaria","1989-08","Corporatizada desde el Ministerio de la Industria del Gas soviético","Instrumento de política exterior energética","Alta"),
 ("CO007","Rosneft","RUS","petroleo","estatal_mayoritaria","1993","Adquirió activos de Yukos tras su quiebra (2004-2007)","","Alta"),
 ("CO008","China National Petroleum Corporation (PetroChina)","CHN","petroleo_gas","estatal","1988","","","Alta"),
 ("CO009","Sinopec","CHN","refino_petroquimica","estatal","1983 (2000 Sinopec Corp)","","Mayor refinador de Asia","Alta"),
 ("CO010","National Iranian Oil Company","IRN","petroleo_gas","estatal","1951","Nacionalización de la Anglo-Iranian (1951)","","Alta"),
 ("CO011","Sonatrach","DZA","petroleo_gas","estatal","1963-12-31","Nacionalización de hidrocarburos (24-02-1971)","Suministro de gas a Europa (Medgaz, Transmed)","Alta"),
 ("CO012","QatarEnergy","QAT","gas_GNL","estatal","1974","Antes Qatar Petroleum","Uno de los mayores exportadores de GNL","Alta"),
 ("CO013","ADNOC","ARE","petroleo_gas","estatal","1971","","","Alta"),
 ("CO014","Equinor","NOR","petroleo_gas_renovables","estatal_mayoritaria (67%)","1972 (Statoil)","OPV 2001","Principal proveedor de gas por gasoducto a Europa desde 2022","Alta"),
 ("CO015","Codelco","CHL","mineria_cobre","estatal","1976-04-01","Nacionalización del cobre (11-07-1971); Ley Reservada del Cobre (financiación militar, derogada 2019)","Mayor productor de cobre del mundo","Alta"),
 ("CO016","Gécamines","COD","mineria_cobre_cobalto","estatal","1967","Nacionalización de la Union Minière (1967)","","Media"),
 ("CO017","Vale","BRA","mineria_hierro_niquel","privada","1942","Privatizada en 1997; desastres de Mariana (2015) y Brumadinho (2019)","","Alta"),
 ("CO018","BHP","AUS","mineria","privada_cotizada","1885","","","Alta"),
 ("CO019","Glencore","CHE","materias_primas_comercio_mineria","privada_cotizada","1974 (Marc Rich + Co)","","Gran productor de cobalto (RDC)","Alta"),
 ("CO020","TSMC","TWN","semiconductores_fundicion","privada_cotizada (Fondo Nacional de Desarrollo ~6%)","1987","","Fabrica la mayoría de chips lógicos más avanzados del mundo; fábricas en EE.UU., Japón y Alemania","Alta"),
 ("CO021","Samsung Electronics","KOR","semiconductores_electronica","privada_cotizada (chaebol)","1969","","Líder en memoria DRAM/NAND","Alta"),
 ("CO022","ASML","NLD","maquinaria_litografia","privada_cotizada","1984","","Monopolio en litografía EUV; sujeta a controles de exportación a China","Alta"),
 ("CO023","NVIDIA","USA","semiconductores_diseno_IA","privada_cotizada","1993","","GPU para IA; controles de exportación a China (2022-)","Alta"),
 ("CO024","Huawei","CHN","telecomunicaciones","privada (propiedad de empleados vía sindicato)","1987","Entity List de EE.UU. (2019)","5G; debate sobre seguridad en redes occidentales","Alta"),
 ("CO025","SMIC","CHN","semiconductores_fundicion","mixta (fondos estatales relevantes)","2000","Entity List (2020)","Producción a 7 nm sin EUV","Alta"),
 ("CO026","Intel","USA","semiconductores","privada_cotizada (participación del gobierno de EE.UU. ~10% en 2025)","1968","CHIPS Act; conversión de subsidios en participación (2025)","","Media"),
 ("CO027","State Grid Corporation of China","CHN","electricidad","estatal","2002","","Mayor empresa eléctrica del mundo","Alta"),
 ("CO028","ICBC","CHN","banca","estatal","1984","","Mayor banco del mundo por activos (varios años)","Alta"),
 ("CO029","JPMorgan Chase","USA","banca","privada_cotizada","2000 (fusión; raíces 1799)","Absorbió Bear Stearns y WaMu (2008), First Republic (2023)","Banco sistémico global","Alta"),
 ("CO030","HSBC","GBR","banca","privada_cotizada","1865","","","Alta"),
 ("CO031","Toyota","JPN","automocion","privada_cotizada","1937","","","Alta"),
 ("CO032","Volkswagen","DEU","automocion","privada_cotizada (Baja Sajonia 20% de votos; Porsche SE)","1937","Fundada por el régimen nazi; privatización parcial 1960","","Alta"),
 ("CO033","BYD","CHN","automocion_baterias","privada_cotizada","1995","","Mayor fabricante de vehículos eléctricos","Alta"),
 ("CO034","CATL","CHN","baterias","privada_cotizada","2011","","Mayor fabricante de baterías de iones de litio","Alta"),
 ("CO035","Tata Group","IND","conglomerado","privada (Tata Sons)","1868","Air India reprivatizada al grupo (2022)","","Alta"),
 ("CO036","Reliance Industries","IND","conglomerado_energia_telecom","privada_cotizada","1966","","Mayor refinería del mundo (Jamnagar)","Alta"),
 ("CO037","A.P. Moller-Maersk","DNK","transporte_maritimo","privada_cotizada","1904","","","Alta"),
 ("CO038","COSCO Shipping","CHN","transporte_maritimo_puertos","estatal","2016 (fusión)","","Participaciones en puertos (El Pireo 2016)","Alta"),
 ("CO039","Siemens","DEU","industria_electrica","privada_cotizada","1847","","","Alta"),
 ("CO040","Hon Hai (Foxconn)","TWN","manufactura_electronica","privada_cotizada","1974","","Ensambla gran parte de los iPhone, mayormente en China","Alta"),
 ("CO041","Apple","USA","tecnologia","privada_cotizada","1976","","Dependencia de cadena de suministro en China","Alta"),
 ("CO042","Microsoft","USA","tecnologia_nube","privada_cotizada","1975","","","Alta"),
 ("CO043","Alphabet (Google)","USA","tecnologia","privada_cotizada","1998","","","Alta"),
 ("CO044","Amazon (AWS)","USA","comercio_nube","privada_cotizada","1994","","Mayor proveedor de nube pública","Alta"),
 ("CO045","Tencent","CHN","tecnologia","privada_cotizada","1998","","WeChat","Alta"),
 ("CO046","Alibaba","CHN","comercio_tecnologia","privada_cotizada","1999","Salida a bolsa de Ant Group suspendida (2020)","","Alta"),
 ("CO047","Gazprom Neft / Lukoil","RUS","petroleo","Lukoil privada; Gazprom Neft filial de Gazprom","1991","Sanciones de EE.UU. a Rosneft y Lukoil (octubre 2025, verificar)","","Baja"),
 ("CO048","Kazatomprom","KAZ","uranio","estatal_mayoritaria","1997","","Mayor productor de uranio del mundo","Alta"),
 ("CO049","Rosatom","RUS","nuclear","estatal","2007","","Construye la mayoría de reactores exportados; enriquecimiento","Alta"),
 ("CO050","Ørsted","DNK","renovables","estatal_mayoritaria (50,1%)","2006 (DONG Energy)","","Eólica marina","Alta"),
 ("CO051","SQM","CHL","litio","privada_cotizada (acuerdo con Codelco 2024-2030)","1968","Privatizada 1983-1988","Litio del Salar de Atacama","Alta"),
 ("CO052","Petronas","MYS","petroleo_gas","estatal","1974","","","Alta"),
 ("CO053","Pertamina","IDN","petroleo_gas","estatal","1957","Crisis de deuda (1975)","","Alta"),
 ("CO054","Nigerian National Petroleum Company","NGA","petroleo_gas","estatal (sociedad anónima desde 2022)","1977","","","Alta"),
 ("CO055","Ecopetrol","COL","petroleo","mixta (88% estatal)","1951","","","Alta"),
 ("CO056","Turkish Petroleum / BOTAŞ","TUR","petroleo_gas","estatal","1954 / 1974","","TurkStream y TANAP","Media"),
]

# reserve_id, country_id, resource, value, unit, ref_date, definition, verification_status, certainty, source_ids
ENERGY_RESERVES = [
 ("RV001","VEN","petroleo",303.8,"miles de millones de barriles","2020-12-31","Reservas probadas (incluye crudos extrapesados del Orinoco)","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV002","SAU","petroleo",297.5,"miles de millones de barriles","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV003","CAN","petroleo",168.1,"miles de millones de barriles","2020-12-31","Incluye arenas bituminosas en desarrollo activo","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV004","IRN","petroleo",157.8,"miles de millones de barriles","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV005","IRQ","petroleo",145.0,"miles de millones de barriles","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV006","RUS","petroleo",107.8,"miles de millones de barriles","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV007","KWT","petroleo",101.5,"miles de millones de barriles","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV008","ARE","petroleo",97.8,"miles de millones de barriles","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV009","USA","petroleo",68.8,"miles de millones de barriles","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV010","LBY","petroleo",48.4,"miles de millones de barriles","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV011","RUS","gas_natural",37.4,"billones de m3","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV012","IRN","gas_natural",32.1,"billones de m3","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV013","QAT","gas_natural",24.7,"billones de m3","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV014","TKM","gas_natural",13.6,"billones de m3","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV015","USA","gas_natural",12.6,"billones de m3","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV016","CHN","gas_natural",8.4,"billones de m3","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV017","VEN","gas_natural",6.3,"billones de m3","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV018","SAU","gas_natural",6.0,"billones de m3","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV019","ARE","gas_natural",5.9,"billones de m3","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
 ("RV020","NGA","gas_natural",5.5,"billones de m3","2020-12-31","Reservas probadas","CONOC_EXPERTO","Media","SRC_EI_SR"),
]

# mineral_id, mineral, stage, dominant_country_ids, share_range_text, ref_period, strategic_use, vulnerability_note, certainty, source_ids
CRITICAL_MINERALS = [
 ("CM001","Tierras raras","extraccion","CHN;USA;MMR;AUS","China ~60-70% de la producción minera mundial","2023-2024","Imanes permanentes (motores eléctricos, misiles, turbinas)","China ~85-90% del refinado; controles de exportación chinos (2023-2025)","Media","SRC_USGS_MCS2025"),
 ("CM002","Tierras raras","refinado_separacion","CHN","~85-90%","2023-2024","","Alto riesgo de concentración","Media","SRC_USGS_MCS2025"),
 ("CM003","Cobalto","extraccion","COD;IDN;RUS;AUS","RDC ~70-75%","2023-2024","Baterías, superaleaciones","Refinado mayoritariamente en China","Media","SRC_USGS_MCS2025"),
 ("CM004","Litio","extraccion","AUS;CHL;CHN;ARG","Australia ~35-50%; Chile ~20-25%","2023-2024","Baterías","'Triángulo del litio' (ARG, BOL, CHL) con grandes recursos","Media","SRC_USGS_MCS2025"),
 ("CM005","Níquel","extraccion","IDN;PHL;RUS;NCL","Indonesia ~50-60%","2023-2024","Acero inoxidable, baterías","Prohibición indonesia de exportar mineral sin procesar (2020)","Media","SRC_USGS_MCS2025"),
 ("CM006","Galio","refinado","CHN","~98%","2023","Semiconductores (GaN, GaAs)","Controles de exportación chinos (agosto 2023) y prohibición a EE.UU. (diciembre 2024)","Media","SRC_USGS_MCS2025"),
 ("CM007","Germanio","refinado","CHN;RUS","China ~60-70%","2023","Fibra óptica, óptica infrarroja","Controles chinos (2023-2024)","Media","SRC_USGS_MCS2025"),
 ("CM008","Grafito natural","extraccion","CHN;MOZ;MDG;BRA","China ~75-80%","2023","Ánodos de baterías","Controles chinos (diciembre 2023)","Media","SRC_USGS_MCS2025"),
 ("CM009","Cobre","extraccion","CHL;PER;COD;CHN;USA","Chile ~23-25%","2023-2024","Electrificación","","Media","SRC_USGS_MCS2025"),
 ("CM010","Uranio","extraccion","KAZ;CAN;NAM;AUS;UZB","Kazajistán ~40%","2022-2023","Combustible nuclear","Enriquecimiento: Rosatom ~40% de la capacidad mundial","Media","SRC_USGS_MCS2025"),
 ("CM011","Platino y paladio","extraccion","ZAF;RUS;ZWE","Sudáfrica ~70% del platino; Rusia ~40% del paladio","2023","Catalizadores, electrónica","","Media","SRC_USGS_MCS2025"),
 ("CM012","Semiconductores lógicos avanzados (<7 nm)","fabricacion","TWN;KOR;USA","Taiwán ~90% (estimaciones sectoriales)","2022-2024","Electrónica, IA, sistemas de armas","Riesgo geopolítico en el Estrecho de Taiwán","Baja","SRC_ACADEMIC_HIST"),
 ("CM013","Polisilicio solar","fabricacion","CHN","~90-95%","2023","Paneles fotovoltaicos","Concentración en Xinjiang; Ley UFLPA de EE.UU. (2022)","Media","SRC_ACADEMIC_HIST"),
 ("CM014","Trigo (exportaciones)","agricultura","RUS;EUU;CAN;AUS;USA;UKR","Rusia ~20% de las exportaciones mundiales","2022-2024","Seguridad alimentaria","Iniciativa de Granos del Mar Negro (07-2022 a 07-2023)","Media","SRC_ACADEMIC_HIST"),
 ("CM015","Fertilizantes potásicos","extraccion","CAN;RUS;BLR;CHN","Canadá ~30-35%; Rusia y Bielorrusia ~35-40% conjuntamente","2021-2023","Agricultura","Sanciones a Bielorrusia (2021-2022)","Media","SRC_USGS_MCS2025"),
]
