# Cambios territoriales y de soberanía, disputas y nodos estratégicos (curado).
# Todas las filas: verification_status = CONOC_EXPERTO salvo indicación.

# change_id, date_start, date_end, territory, from_ids, to_ids, change_type, legal_status_note, description, certainty, source_ids
TERRITORIAL_CHANGES = [
 ("TC001", "1945-05-08", "1949-10-07", "Alemania", "DEU", "DEU;DDR", "ocupacion_y_particion", "Ocupación aliada en 4 zonas; RFA (23-05-1949) y RDA (07-10-1949)", "Rendición alemana y división del país; los territorios al este de la línea Óder-Neisse pasan a administración polaca y soviética (Conferencia de Potsdam).", "Alta", "SRC_ACADEMIC_HIST;SRC_BRITANNICA"),
 ("TC002", "1945-08-02", "1945-08-02", "Prusia Oriental septentrional (Königsberg/Kaliningrado)", "DEU", "RUS", "anexion_tratado_posguerra", "Acuerdo de Potsdam; reconocimiento definitivo en Tratado 2+4 (1990)", "Transferencia a la URSS (RSFS de Rusia); expulsión de población alemana.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC003", "1945-08-02", "1990-11-14", "Territorios al este del Óder-Neisse", "DEU", "POL", "transferencia_posguerra", "Potsdam 1945; Tratado germano-polaco de fronteras 14-11-1990", "Pomerania, Silesia y sur de Prusia Oriental pasan a Polonia; desplazamiento masivo de población.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC004", "1945-09-02", "", "Islas Kuriles del sur / 'Territorios del Norte'", "JPN", "RUS", "ocupacion_militar_disputada", "Japón reclama Etorofu, Kunashiri, Shikotan y Habomai; sin tratado de paz ruso-japonés", "Ocupación soviética en agosto-septiembre de 1945; disputa vigente.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC005", "1947-08-15", "1947-08-15", "India británica", "GBR", "IND;PAK", "particion_independencia", "Indian Independence Act 1947", "Partición en India y Pakistán (Occidental y Oriental); 10-20 millones de desplazados y entre 200.000 y 2 millones de muertos según estimaciones.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC006", "1947-10-26", "", "Cachemira", "", "IND;PAK;CHN", "disputa_territorial_armada", "Línea de Control desde 1972 (Acuerdo de Simla); Aksai Chin bajo control chino", "Adhesión del maharajá a India y primera guerra indo-pakistaní; partición de facto.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC007", "1948-05-14", "1949-07-20", "Palestina del Mandato", "GBR", "ISR;JOR;EGY", "independencia_y_guerra", "Líneas de armisticio de 1949 ('Línea Verde')", "Fin del Mandato británico, independencia de Israel; Cisjordania bajo Jordania y Gaza bajo Egipto.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC008", "1949-12-27", "1949-12-27", "Indias Orientales Neerlandesas", "NLD", "IDN", "independencia", "Transferencia de soberanía reconocida en la Conferencia de La Haya", "Independencia de Indonesia (proclamada 17-08-1945).", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC009", "1950-10-07", "1951-05-23", "Tíbet", "TBT", "CHN", "anexion_militar", "Acuerdo de 17 puntos (1951)", "Entrada del EPL y control de la RPC; exilio del Dalai Lama en 1959.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC010", "1954-07-21", "1976-07-02", "Vietnam", "FRA", "VNM;VDR", "particion_y_reunificacion", "Acuerdos de Ginebra 1954 (paralelo 17); reunificación formal 02-07-1976", "Partición tras Dien Bien Phu y posterior reunificación bajo Hanói tras la caída de Saigón (30-04-1975). VDR = República de Vietnam (código V-Dem).", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC011", "1954-10-05", "1975-11-10", "Trieste", "", "ITA;SRB", "particion_negociada", "Memorándum de Londres 1954; Tratado de Osimo 1975", "Zona A a Italia y Zona B a Yugoslavia.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC012", "1957-01-01", "1957-01-01", "Sarre", "FRA", "DEU", "reintegracion_referendum", "Referéndum de 1955 y Tratado de Luxemburgo 1956", "El Sarre se integra en la RFA.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC013", "1961-12-19", "1961-12-19", "Goa, Damán y Diu", "PRT", "IND", "anexion_militar", "Reconocida por Portugal en 1974", "Operación Vijay de India.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC014", "1962-10-20", "", "Aksai Chin / Arunachal Pradesh", "IND", "CHN", "guerra_fronteriza_disputa", "Línea de Control Real (LAC) no demarcada", "Guerra chino-india; China mantiene Aksai Chin y reclama Arunachal Pradesh.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC015", "1967-06-10", "", "Cisjordania, Jerusalén Este, Gaza, Sinaí, Golán", "JOR;EGY;SYR", "ISR", "ocupacion_militar", "Res. 242 CSNU; Sinaí devuelto 1982; Gaza desconectada 2005; Jerusalén Este (1980) y Golán (1981) anexionados sin reconocimiento internacional mayoritario", "Guerra de los Seis Días.", "Alta", "SRC_ACADEMIC_HIST;SRC_UNTC"),
 ("TC016", "1971-12-16", "1971-12-16", "Pakistán Oriental", "PAK", "BGD", "secesion_guerra", "Reconocimiento por Pakistán en 1974", "Independencia de Bangladés tras guerra de liberación e intervención india.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC017", "1972-05-15", "1972-05-15", "Okinawa (Islas Ryukyu)", "USA", "JPN", "devolucion_administrativa", "Acuerdo de reversión de Okinawa 1971", "EE.UU. devuelve la administración a Japón conservando bases.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC018", "1974-07-20", "", "Norte de Chipre", "CYP", "TUR", "ocupacion_militar_estado_no_reconocido", "RTNC proclamada 1983, reconocida solo por Turquía", "Intervención turca tras golpe pro-enosis.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC019", "1975-05-16", "1975-05-16", "Sikkim", "SKM", "IND", "anexion_referendum", "Referéndum de abril de 1975", "Sikkim se convierte en estado de la India.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC020", "1975-11-14", "", "Sáhara Occidental", "ESP", "MAR;MRT", "descolonizacion_disputada", "Acuerdos de Madrid 1975; Mauritania se retira 1979; RASD proclamada 1976; territorio no autónomo según ONU", "Marcha Verde y control marroquí de ~75-80% del territorio; Frente Polisario.", "Alta", "SRC_ACADEMIC_HIST;SRC_UN_MEMBERS"),
 ("TC021", "1975-12-07", "2002-05-20", "Timor Oriental", "PRT", "IDN;TLS", "invasion_y_posterior_independencia", "Referéndum ONU 30-08-1999; independencia 20-05-2002", "Invasión indonesia; ocupación hasta 1999; administración ONU (UNTAET).", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC022", "1982-04-25", "1982-04-25", "Península del Sinaí", "ISR", "EGY", "devolucion_tratado", "Tratado de paz egipcio-israelí 1979", "Retirada israelí completa del Sinaí (Taba en 1989 por arbitraje).", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC023", "1982-04-02", "1982-06-14", "Islas Malvinas/Falkland", "GBR", "ARG", "ocupacion_temporal_revertida", "Soberanía disputada por Argentina; control británico restablecido", "Guerra de las Malvinas.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC024", "1990-05-22", "1990-05-22", "Yemen", "YEM;YMD", "YEM", "unificacion", "Unificación de la RAY y la RDPY", "Guerra civil de secesión del sur en 1994 fallida.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC025", "1990-03-21", "1994-03-01", "Namibia / Walvis Bay", "ZAF", "NAM", "independencia", "Res. 435 CSNU; Walvis Bay transferida en 1994", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC026", "1990-08-02", "1991-02-28", "Kuwait", "KWT", "IRQ", "anexion_revertida", "Res. 660/678 CSNU", "Invasión y anexión iraquí revertida por coalición internacional.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC027", "1990-10-03", "1990-10-03", "República Democrática Alemana", "DDR", "DEU", "reunificacion", "Tratado 2+4 (12-09-1990)", "Adhesión de la RDA a la RFA.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC028", "1991-06-25", "1992-04-27", "Yugoslavia (RFSY)", "SRB", "SVN;HRV;MKD;BIH;SRB", "disolucion", "Comisión Badinter; RF Yugoslavia (Serbia-Montenegro) 1992", "Disolución violenta de la federación yugoslava.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC029", "1991-12-26", "1991-12-26", "Unión Soviética", "RUS", "RUS;UKR;BLR;KAZ;UZB;TKM;KGZ;TJK;GEO;ARM;AZE;MDA;LTU;LVA;EST", "disolucion", "Acuerdos de Belavezha (08-12-1991) y Alma-Ata; bálticos reconocidos en septiembre de 1991", "Rusia continuadora de la URSS en el CSNU.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC030", "1993-01-01", "1993-01-01", "Checoslovaquia", "CZE", "CZE;SVK", "disolucion_pacifica", "'Divorcio de terciopelo'", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC031", "1993-05-24", "1993-05-24", "Eritrea", "ETH", "ERI", "secesion_referendum", "Referéndum de abril de 1993", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC032", "1994-05-16", "", "Nagorno Karabaj y distritos adyacentes", "AZE", "ARM", "ocupacion_militar_estado_no_reconocido", "Alto el fuego de Biskek 1994", "Control armenio de facto hasta 2020-2023.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC033", "1997-07-01", "1997-07-01", "Hong Kong", "GBR", "CHN", "retrocesion", "Declaración Conjunta Sino-Británica 1984 ('un país, dos sistemas')", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC034", "1999-12-20", "1999-12-20", "Macao", "PRT", "CHN", "retrocesion", "Declaración Conjunta Sino-Portuguesa 1987", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC035", "1999-12-31", "1999-12-31", "Zona del Canal de Panamá", "USA", "PAN", "transferencia_tratado", "Tratados Torrijos-Carter 1977", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC036", "2006-06-03", "2006-06-05", "Serbia y Montenegro", "SRB", "SRB;MNE", "disolucion_referendum", "Referéndum montenegrino 21-05-2006", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC037", "2008-02-17", "", "Kosovo", "SRB", "XKX", "secesion_reconocimiento_parcial", "Opinión consultiva CIJ 2010: la declaración no violó el derecho internacional; reconocimiento parcial", "Administración ONU desde 1999 (Res. 1244).", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC038", "2008-08-26", "", "Abjasia y Osetia del Sur", "GEO", "RUS", "secesion_reconocimiento_ruso", "Reconocidas por Rusia y pocos estados; consideradas territorios ocupados por Georgia y la UE", "Guerra ruso-georgiana.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC039", "2008-08-14", "2008-08-14", "Península de Bakassi", "NGA", "CMR", "transferencia_fallo_judicial", "Sentencia CIJ 2002; Acuerdo de Greentree 2006", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC040", "2011-07-09", "2011-07-09", "Sudán del Sur", "SDN", "SSD", "secesion_referendum", "Acuerdo General de Paz 2005; referéndum enero 2011", "Abyei sigue disputado.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC041", "2014-03-18", "", "Crimea y Sebastopol", "UKR", "RUS", "anexion_no_reconocida", "Res. AGNU 68/262 afirma la integridad territorial de Ucrania", "Anexión rusa tras ocupación militar y referéndum no reconocido.", "Alta", "SRC_ACADEMIC_HIST;SRC_UNTC"),
 ("TC042", "2014-04-06", "2022-09-30", "Donetsk y Lugansk (partes)", "UKR", "RUS", "secesion_apoyada_externamente", "'Repúblicas populares' apoyadas por Rusia; reconocidas por Rusia 21-02-2022", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC043", "2022-09-30", "", "Óblasts de Donetsk, Lugansk, Zaporiyia y Jersón (partes)", "UKR", "RUS", "anexion_no_reconocida", "Res. AGNU ES-11/4 (12-10-2022) condena la anexión", "Rusia controla parcialmente los cuatro óblasts; frente activo.", "Alta", "SRC_ACADEMIC_HIST;SRC_UNTC"),
 ("TC044", "2019-08-05", "2019-10-31", "Jammu y Cachemira (India)", "IND", "IND", "reorganizacion_interna", "Revocación del artículo 370", "Pérdida de autonomía; división en dos territorios de la Unión.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC045", "2020-11-10", "2023-10-01", "Nagorno Karabaj", "ARM", "AZE", "reconquista_militar", "Declaración trilateral 10-11-2020; ofensiva azerí sept. 2023; disolución de la 'República de Artsaj' 01-01-2024", "Éxodo de >100.000 armenios de Karabaj en 2023.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC046", "1960-06-26", "1960-07-01", "Somalilandia británica y Somalia italiana", "GBR;ITA", "SOM", "independencia_union", "Somalilandia proclama independencia en 1991 sin reconocimiento", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC047", "1962-07-05", "1962-07-05", "Argelia", "FRA", "DZA", "independencia_guerra", "Acuerdos de Evian; referéndum", "Fin de la guerra de independencia (1954-1962).", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC048", "1965-08-09", "1965-08-09", "Singapur", "MYS", "SGP", "expulsion_independencia", "", "Separación de la Federación de Malasia.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC049", "1975-11-11", "1975-11-11", "Angola", "PRT", "AGO", "independencia", "Acuerdo de Alvor; tras Revolución de los Claveles", "Mozambique (25-06-1975), Guinea-Bisáu (1974), Cabo Verde y Santo Tomé (1975) en el mismo proceso.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC050", "1980-04-18", "1980-04-18", "Rodesia del Sur", "GBR", "ZWE", "independencia", "Acuerdo de Lancaster House 1979", "Tras la declaración unilateral de independencia de Rodesia (1965).", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC051", "1994-05-30", "1994-05-30", "Franja de Aouzou", "LBY", "TCD", "devolucion_fallo_judicial", "Sentencia CIJ 1994", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC052", "1998-10-26", "1998-10-26", "Frontera Ecuador-Perú (Cordillera del Cóndor)", "ECU;PER", "ECU;PER", "acuerdo_limites", "Acta Presidencial de Brasilia", "Cierra la disputa tras guerras de 1941, 1981 y 1995 (Cenepa).", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC053", "1904-10-20", "", "Litoral boliviano (Antofagasta)", "BOL", "CHL", "cesion_tratado_posguerra", "Tratado de Paz y Amistad 1904; CIJ 2018 rechazó obligación de negociar acceso soberano", "Consecuencia de la Guerra del Pacífico (1879-1884); Bolivia sin litoral.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC054", "1935-06-12", "1938-07-21", "Chaco Boreal", "BOL", "PRY", "conquista_tratado", "Tratado de Paz, Amistad y Límites 1938", "Guerra del Chaco.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC055", "1899-10-03", "", "Guayana Esequiba", "VEN", "GUY", "disputa_territorial", "Laudo de París 1899 impugnado por Venezuela; Acuerdo de Ginebra 1966; caso ante la CIJ (desde 2018); referéndum venezolano 03-12-2023", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC056", "1940-03-13", "1947-02-10", "Carelia, Petsamo", "FIN", "RUS", "cesion_tratado_posguerra", "Tratado de Moscú 1940; Tratado de París 1947", "Guerra de Invierno y Guerra de Continuación.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC057", "1940-06-17", "1991-09-06", "Estados bálticos", "EST;LVA;LTU", "RUS", "ocupacion_anexion_revertida", "Ocupación soviética no reconocida por muchos estados occidentales; restauración de independencia 1990-1991", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC058", "1939-06-29", "1939-06-29", "Hatay (Alejandreta)", "SYR", "TUR", "anexion_tratado_mandato", "Cesión de la Francia mandataria; Siria no reconoce", "", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC059", "1949-10-01", "", "Taiwán", "CHN", "TWN", "division_postguerra_civil", "La RPC reclama soberanía; reconocimiento diplomático de la RDC limitado; Res. AGNU 2758 (1971) transfirió el asiento chino a la RPC", "Retirada del gobierno de la República de China a Taiwán tras la guerra civil.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC060", "1953-07-27", "", "Península de Corea", "KOR;PRK", "KOR;PRK", "armisticio_division", "Acuerdo de Armisticio de Corea; sin tratado de paz", "Zona desmilitarizada aprox. en el paralelo 38.", "Alta", "SRC_ACADEMIC_HIST"),
 ("TC061", "2025-05-22", "", "Archipiélago de Chagos (Diego García)", "GBR", "MUS", "transferencia_soberania_con_arrendamiento", "Tratado Reino Unido-Mauricio firmado 22-05-2025; base de Diego García arrendada por 99 años; Opinión consultiva CIJ 2019", "Ratificación y entrada en vigor pendientes de verificar a la fecha de corte.", "Media", "SRC_ACADEMIC_HIST"),
]

# dispute_id, name, claimants, controller, type, since, status, strategic_value, notes, certainty
DISPUTES = [
 ("DSP001", "Cachemira", "IND;PAK;CHN", "IND;PAK;CHN (dividido)", "territorial_armada", "1947", "activa", "Alta: agua (Indo), posición militar, identidad nacional", "Tres guerras indo-pakistaníes relacionadas (1947, 1965, 1999 Kargil) y crisis de 2016, 2019 y 2025.", "Alta"),
 ("DSP002", "Taiwán", "CHN;TWN", "TWN", "soberania", "1949", "activa", "Muy alta: semiconductores, primera cadena de islas", "Riesgo de bloqueo/invasión; EE.UU. con ambigüedad estratégica (Taiwan Relations Act 1979).", "Alta"),
 ("DSP003", "Mar de China Meridional (Spratly, Paracel, Scarborough)", "CHN;VNM;PHL;MYS;BRN;TWN", "Mixto", "maritima_insular", "1947 ('línea de nueve trazos')", "activa", "Muy alta: rutas comerciales, pesca, hidrocarburos", "Laudo arbitral CPA 2016 (Filipinas c. China) rechaza la línea de nueve trazos; China no lo acepta.", "Alta"),
 ("DSP004", "Islas Senkaku/Diaoyu", "JPN;CHN;TWN", "JPN", "insular", "1971", "activa", "Media-alta", "Incluidas en el ámbito del tratado de seguridad EE.UU.-Japón según declaraciones oficiales estadounidenses.", "Alta"),
 ("DSP005", "Kuriles del sur", "JPN;RUS", "RUS", "insular", "1945", "activa", "Media", "", "Alta"),
 ("DSP006", "Dokdo/Takeshima", "KOR;JPN", "KOR", "insular", "1952", "activa", "Baja-media", "", "Alta"),
 ("DSP007", "Sáhara Occidental", "MAR;RASD(Polisario)", "MAR (~80%)", "descolonizacion", "1975", "activa", "Media: fosfatos, pesca", "EE.UU. reconoció la soberanía marroquí en 2020.", "Alta"),
 ("DSP008", "Malvinas/Falkland, Georgias y Sandwich del Sur", "ARG;GBR", "GBR", "insular", "1833", "activa_diplomatica", "Media: pesca, hidrocarburos, Antártida", "", "Alta"),
 ("DSP009", "Esequibo", "VEN;GUY", "GUY", "territorial", "1899/1962", "activa", "Alta: petróleo offshore (Stabroek)", "Caso ante la CIJ.", "Alta"),
 ("DSP010", "Crimea y territorios ocupados de Ucrania", "UKR;RUS", "RUS", "anexion_guerra", "2014", "activa_guerra", "Muy alta", "", "Alta"),
 ("DSP011", "Altos del Golán", "SYR;ISR", "ISR", "ocupacion", "1967", "activa", "Alta: agua, altura militar", "EE.UU. reconoció la soberanía israelí en 2019.", "Alta"),
 ("DSP012", "Cisjordania y Jerusalén Este", "PSE;ISR", "ISR (y ANP en áreas A/B)", "ocupacion", "1967", "activa", "Muy alta", "", "Alta"),
 ("DSP013", "Chipre del Norte", "CYP;TUR", "TUR/RTNC", "ocupacion", "1974", "activa", "Media", "", "Alta"),
 ("DSP014", "Abjasia y Osetia del Sur", "GEO;RUS", "RUS (protectorados)", "secesion", "1992/2008", "activa", "Media", "", "Alta"),
 ("DSP015", "Transnistria", "MDA;RUS(apoyo)", "Autoridades separatistas", "secesion", "1992", "congelada", "Baja-media", "Presencia militar rusa.", "Alta"),
 ("DSP016", "Línea de Control Real chino-india (Ladakh, Arunachal)", "IND;CHN", "Mixto", "frontera_no_demarcada", "1962", "activa", "Alta", "Choque del valle de Galwan, junio 2020.", "Alta"),
 ("DSP017", "Abyei", "SDN;SSD", "Administración interina / UNISFA", "territorial", "2011", "activa", "Media: petróleo", "", "Alta"),
 ("DSP018", "Triángulo de Hala'ib", "EGY;SDN", "EGY", "territorial", "1958", "latente", "Baja", "", "Alta"),
 ("DSP019", "Gibraltar", "ESP;GBR", "GBR", "soberania", "1713", "diplomatica", "Media: estrecho", "Tratado de Utrecht.", "Alta"),
 ("DSP020", "Acceso soberano al mar de Bolivia", "BOL;CHL", "CHL", "reivindicacion_maritima", "1884/1904", "cerrada_judicialmente_2018", "Media", "CIJ 2018: Chile no tiene obligación de negociar.", "Alta"),
 ("DSP021", "Belice (reclamación guatemalteca)", "GTM;BLZ", "BLZ", "territorial", "1859", "ante_CIJ", "Baja", "Ambos países sometieron el caso a la CIJ por referéndums (2018, 2019).", "Alta"),
 ("DSP022", "Ártico (plataforma continental extendida)", "RUS;CAN;DNK;NOR;USA", "Mixto", "maritima", "2001", "activa_juridica", "Alta: rutas, recursos", "Presentaciones ante la CLPC.", "Media"),
 ("DSP023", "Kosovo", "SRB;XKX", "XKX", "secesion_reconocimiento_parcial", "2008", "activa_diplomatica", "Media", "", "Alta"),
 ("DSP024", "Nagorno Karabaj", "ARM;AZE", "AZE desde 2023", "territorial", "1988", "resuelta_militarmente_2023", "Media", "", "Alta"),
 ("DSP025", "Franja de Gaza", "PSE;ISR", "Guerra/ocupación desde 2023", "conflicto_armado", "2007/2023", "activa_guerra", "Alta", "", "Alta"),
]

# node_id, name, type, country_ids, lat, lon, strategic_function, metric, metric_value, metric_unit, metric_year, metric_source, certainty, notes
STRATEGIC_NODES = [
 ("NODE001", "Estrecho de Ormuz", "estrecho", "IRN;OMN", 26.57, 56.25, "Salida del Golfo Pérsico: petróleo y GNL de Arabia Saudí, EAU, Kuwait, Irak, Irán y Catar", "flujo_petroleo", 18.5, "millones b/d", 2016, "SRC_EIA_CHOKE", "Media", "Cifra 2016 de EIA (edición 2017) obtenida por buscador; ~1/5 del consumo mundial de líquidos según EIA. Valor de 2023 no verificado."),
 ("NODE002", "Estrecho de Malaca", "estrecho", "MYS;IDN;SGP", 2.50, 101.50, "Ruta principal Índico-Pacífico; suministro energético de China, Japón y Corea", "flujo_petroleo", 23.7, "millones b/d", 2023, "SRC_EIA_CHOKE", "Media", "Cifra 2023 atribuida a EIA vía resumen de Statista (búsqueda web)."),
 ("NODE003", "Canal de Suez y oleoducto SUMED", "canal", "EGY", 30.58, 32.27, "Conexión Mediterráneo-Mar Rojo", "flujo_petroleo", 5.5, "millones b/d", 2016, "SRC_EIA_CHOKE", "Media", "Flujos reducidos desde finales de 2023 por ataques hutíes en el Mar Rojo."),
 ("NODE004", "Bab el-Mandeb", "estrecho", "YEM;DJI;ERI", 12.58, 43.33, "Mar Rojo-Golfo de Adén", "", None, "", None, "SRC_EIA_CHOKE", "Media", "Ataques hutíes 2023-2024 desviaron tráfico por el Cabo de Buena Esperanza."),
 ("NODE005", "Bósforo y Dardanelos (Estrechos Turcos)", "estrecho", "TUR", 41.12, 29.07, "Salida del Mar Negro; régimen de la Convención de Montreux (1936)", "", None, "", None, "SRC_EIA_CHOKE", "Alta", "Turquía cerró el paso a buques de guerra beligerantes en 2022 invocando Montreux."),
 ("NODE006", "Canal de Panamá", "canal", "PAN", 9.08, -79.68, "Conexión Atlántico-Pacífico", "", None, "", None, "SRC_EIA_CHOKE", "Alta", "Sequía 2023-2024 restringió tránsitos."),
 ("NODE007", "Estrecho de Taiwán", "estrecho", "CHN;TWN", 24.50, 119.50, "Ruta comercial clave de Asia Oriental", "", None, "", None, "", "Alta", ""),
 ("NODE008", "Estrecho de Gibraltar", "estrecho", "ESP;MAR;GBR", 35.97, -5.50, "Mediterráneo-Atlántico", "", None, "", None, "", "Alta", ""),
 ("NODE009", "Paso GIUK (Groenlandia-Islandia-Reino Unido)", "paso_maritimo", "GRL;ISL;GBR", 63.0, -15.0, "Acceso de la Flota del Norte rusa al Atlántico; vigilancia antisubmarina OTAN", "", None, "", None, "", "Alta", ""),
 ("NODE010", "Brecha de Suwałki", "corredor_terrestre", "POL;LTU", 54.10, 23.10, "Única conexión terrestre de los bálticos con Polonia, entre Bielorrusia y Kaliningrado", "", None, "", None, "", "Alta", ""),
 ("NODE011", "Estrecho de Lombok y Sunda", "estrecho", "IDN", -8.5, 115.7, "Rutas alternativas a Malaca", "", None, "", None, "", "Alta", ""),
 ("NODE012", "Cabo de Buena Esperanza", "ruta_alternativa", "ZAF", -34.36, 18.47, "Ruta alternativa a Suez", "", None, "", None, "", "Alta", ""),
 ("NODE013", "Corredor de Wakhan", "corredor_terrestre", "AFG", 37.0, 73.5, "Conexión Afganistán-China", "", None, "", None, "", "Alta", ""),
 ("NODE014", "Corredor de Siliguri ('cuello de pollo')", "corredor_terrestre", "IND", 26.7, 88.4, "Conecta el noreste de India con el resto del país", "", None, "", None, "", "Alta", ""),
 ("NODE015", "Ruta Marítima del Norte", "ruta_maritima", "RUS", 75.0, 100.0, "Ruta ártica Europa-Asia, estacional", "", None, "", None, "", "Alta", ""),
 ("NODE016", "Puerto de Shanghái", "puerto", "CHN", 31.23, 121.47, "Mayor puerto de contenedores del mundo", "", None, "", None, "", "Alta", "Volumen TEU no verificado en sesión; ver WDI is_shp_good_tu por país."),
 ("NODE017", "Puerto de Singapur", "puerto", "SGP", 1.26, 103.84, "Hub de trasbordo global", "", None, "", None, "", "Alta", ""),
 ("NODE018", "Puerto de Róterdam", "puerto", "NLD", 51.95, 4.14, "Mayor puerto de Europa", "", None, "", None, "", "Alta", ""),
 ("NODE019", "Oleoducto Druzhba", "oleoducto", "RUS;BLR;UKR;POL;HUN;SVK;CZE;DEU", 52.0, 30.0, "Suministro de crudo ruso a Europa Central", "", None, "", None, "", "Alta", "Exentos parcialmente del embargo UE de 2022 (Hungría, Eslovaquia)."),
 ("NODE020", "Gasoductos Nord Stream 1 y 2", "gasoducto", "RUS;DEU", 55.0, 15.0, "Gas ruso a Alemania por el Báltico", "", None, "", None, "", "Alta", "Dañados por explosiones el 26-09-2022; autoría objeto de investigaciones judiciales."),
 ("NODE021", "Oleoducto Este-Oeste saudí (Petroline)", "oleoducto", "SAU", 25.0, 45.0, "Bypass parcial de Ormuz hacia Yanbu (Mar Rojo)", "", None, "", None, "", "Alta", ""),
 ("NODE022", "Gasoducto Power of Siberia", "gasoducto", "RUS;CHN", 52.0, 127.0, "Gas ruso a China (operativo desde dic. 2019)", "", None, "", None, "", "Alta", ""),
 ("NODE023", "TSMC Hsinchu / Tainan (fabs avanzadas)", "industria_critica", "TWN", 24.78, 120.99, "Producción de la mayoría de chips lógicos de vanguardia del mundo", "", None, "", None, "", "Alta", "Cuota exacta no verificada en sesión."),
 ("NODE024", "Cable submarino y nodos de Internet del Mar Rojo/Egipto", "infraestructura_digital", "EGY", 31.2, 29.9, "Gran parte del tráfico de datos Europa-Asia transita por Egipto", "", None, "", None, "", "Media", ""),
 ("NODE025", "Presa de las Tres Gargantas", "energia_hidroelectrica", "CHN", 30.82, 111.0, "Mayor central hidroeléctrica del mundo por capacidad (22,5 GW)", "capacidad", 22.5, "GW", 2012, "", "Alta", ""),
 ("NODE026", "Gran Presa del Renacimiento Etíope (GERD)", "energia_hidroelectrica", "ETH", 11.21, 35.09, "Control del Nilo Azul; disputa con Egipto y Sudán", "", None, "", None, "", "Alta", ""),
 ("NODE027", "Central nuclear de Zaporiyia", "energia_nuclear", "UKR", 47.51, 34.59, "Mayor central nuclear de Europa (6 reactores); ocupada por Rusia desde marzo de 2022", "", None, "", None, "SRC_IAEA_PRIS", "Alta", ""),
 ("NODE028", "Base Naval de Sebastopol", "base_militar", "UKR;RUS", 44.6, 33.53, "Flota del Mar Negro rusa (Crimea ocupada por Rusia desde 2014; territorio ucraniano según la ONU)", "", None, "", None, "", "Alta", ""),
 ("NODE029", "Diego García", "base_militar", "GBR;USA", -7.31, 72.42, "Base aeronaval en el Índico", "", None, "", None, "", "Alta", ""),
 ("NODE030", "Guam", "base_militar", "USA", 13.44, 144.79, "Proyección de poder en el Pacífico occidental", "", None, "", None, "", "Alta", ""),
 ("NODE031", "Yibuti (bases extranjeras)", "base_militar", "DJI", 11.59, 43.15, "Bases de EE.UU., Francia, China, Japón e Italia", "", None, "", None, "", "Alta", ""),
 ("NODE032", "Ramstein", "base_militar", "DEU", 49.44, 7.6, "Principal base aérea de EE.UU. en Europa", "", None, "", None, "", "Alta", ""),
]
