# Escenarios históricos de inicio de partida (curado). Las instantáneas cuantitativas por país se generan
# automáticamente en 34b_ESCENARIOS_PAISES a partir de las series (con el año del dato utilizado, sin mezclar épocas).

# scenario_id, name, start_date, reference_region, focus_countries, political_situation, economic_conditions, military_capabilities,
# international_relations, active_conflict_ids, social_situation, institutions, recent_events, threats, opportunities, missing_data, notes, source_ids
SCENARIOS = [
 ("SC1946","Nuevo orden de posguerra","1946-01-01","GLOBAL","USA;RUS;GBR;FRA;CHN;DEU;JPN;IND",
  "Ocupación de Alemania y Japón; Partido Laburista en el Reino Unido; guerra civil china reanudándose","Destrucción de Europa y Asia oriental; EE.UU. ~ la mitad de la producción industrial mundial (estimación historiográfica); Bretton Woods","Monopolio nuclear de EE.UU.; desmovilización masiva","ONU recién creada; tensiones soviético-occidentales (discurso del 'Telón de Acero', 05-03-1946)","CF001;CF005","Desplazamientos masivos; reconstrucción","Ocupaciones militares; monarquías y democracias restauradas","Fin de la Segunda Guerra Mundial (09-1945)","Expansión soviética; colapso económico europeo","Reconstrucción, descolonización","Series WDI no existen antes de 1960: usar COW NMC, Maddison, V-Dem","Muchos Estados actuales no existen aún (ver 03_ESTADOS: fechas de inicio)","SRC_ACADEMIC_HIST;SRC_COW_WEB"),
 ("SC1950","Guerra de Corea","1950-06-25","Asia oriental","KOR;PRK;CHN;USA;RUS;JPN;TWN",
  "Mao en el poder; Kim Il-sung ataca el Sur; McCarthismo en EE.UU.","Recuperación europea con Plan Marshall","URSS con bomba atómica desde 1949","OTAN (1949); alianza sino-soviética (02-1950)","CF004;CF005","","","Victoria comunista en China (1949)","Guerra general en Asia","Rearme occidental (NSC-68)","Pocas series económicas para Asia","","SRC_ACADEMIC_HIST"),
 ("SC1956","Suez y Hungría","1956-10-23","Europa/Oriente Medio","EGY;GBR;FRA;ISR;HUN;RUS;USA",
  "Desestalinización; nacionalismo árabe de Nasser","Crecimiento de posguerra en Occidente","Ambas superpotencias con bombas H","Crisis simultáneas en ambos bloques","CF007;CF008;CF006","","","Discurso secreto de Jruschov (02-1956); nacionalización del Canal (07-1956)","Escalada entre superpotencias","Descolonización árabe","","","SRC_ACADEMIC_HIST"),
 ("SC1960","Descolonización africana","1960-01-01","África","COD;NGA;GHA;SEN;CIV;FRA;GBR;BEL;ZAF",
  "17 independencias en 1960; apartheid sudafricano","Economías primarias exportadoras","Ejércitos coloniales en transición","Competencia de la Guerra Fría por los nuevos Estados","CF006","Fronteras coloniales heterogéneas","Constituciones heredadas (Westminster/francesa)","Conferencia de Bandung (1955)","Golpes, secesiones (Katanga)","Ayuda internacional, nacionalización de recursos","Datos estadísticos escasos para los primeros años","Inicio de las series WDI (1960)","SRC_ACADEMIC_HIST"),
 ("SC1962","Crisis de los misiles en Cuba","1962-10-16","Américas","USA;CUB;RUS;TUR",
  "Kennedy y Jruschov","","Superioridad estratégica de EE.UU. ('missile gap' inexistente)","Confrontación nuclear directa","CF010;CF009","","","Bahía de Cochinos (1961); Muro de Berlín (1961)","Guerra nuclear","Distensión posterior","","","SRC_ACADEMIC_HIST;SRC_FRUS"),
 ("SC1973","Shock petrolero y Yom Kipur","1973-10-06","Oriente Medio/Global","EGY;SYR;ISR;SAU;USA;RUS;IRN;JPN",
  "Watergate en EE.UU.; Sadat en Egipto","Fin de Bretton Woods; inflación creciente","","Distensión entre superpotencias; acercamiento EE.UU.-China","CF016;CF009","","","Golpe en Chile (09-1973)","Escalada superpotencias (DEFCON 3)","Poder de la OPEP","","","SRC_ACADEMIC_HIST"),
 ("SC1979","Año de las rupturas","1979-01-01","Global","IRN;AFG;RUS;USA;CHN;GBR;NIC",
  "Revolución iraní, Thatcher, reformas de Deng, revolución sandinista","Segundo shock petrolero; shock Volcker inminente","","Fin de la distensión tras Afganistán (12-1979)","CF021;CF022;CF054","","","","","","","","SRC_ACADEMIC_HIST"),
 ("SC1982","Crisis de la deuda latinoamericana y Malvinas","1982-04-02","América Latina","ARG;GBR;MEX;BRA;CHL;USA",
  "Dictaduras en el Cono Sur","Tipos de interés de EE.UU. muy altos; default mexicano en agosto","","","CF023;CF053;CF054","","","","","","","","SRC_ACADEMIC_HIST"),
 ("SC1989","Caída del Muro de Berlín","1989-11-09","Europa","DEU;DDR;POL;HUN;CZE;RUS;USA;FRA;GBR",
  "Revoluciones en Europa del Este; Gorbachov","Colapso de las economías planificadas","Pacto de Varsovia en desintegración","Fin de la Guerra Fría","CF021","","","Tiananmén (06-1989)","Violencia en transiciones (Rumanía)","Reunificación alemana, integración europea","","","SRC_ACADEMIC_HIST"),
 ("SC1991","Disolución de la URSS","1991-12-26","Eurasia","RUS;UKR;BLR;KAZ;GEO;ARM;AZE;MDA;EST;LVA;LTU",
  "15 Estados nuevos; Yeltsin","Hiperinflación y colapso del PIB postsoviético","Arsenal nuclear en 4 Estados","Unipolaridad de EE.UU.","CF025;CF044","","Instituciones en construcción","Golpe fallido de agosto de 1991; Guerra del Golfo","Conflictos étnicos; armas nucleares sueltas","Democratización, integración a Occidente","Series WDI de los nuevos Estados empiezan ~1990-1995","","SRC_ACADEMIC_HIST"),
 ("SC1997","Crisis financiera asiática","1997-07-02","Asia","THA;IDN;KOR;MYS;PHL;JPN;CHN;HKG",
  "Retrocesión de Hong Kong (07-1997)","Tipos de cambio fijos con deuda de corto plazo en USD","","","","","","","Contagio (Rusia 1998, Brasil 1999)","","","","SRC_LAEVEN_VALENCIA"),
 ("SC2001","11 de septiembre","2001-09-11","Global","USA;AFG;PAK;IRQ;SAU;GBR",
  "Bush; talibanes en Afganistán","Recesión de las punto com","","Unipolaridad; 'guerra contra el terror'","CF033","","","","Terrorismo transnacional","Coalición global","","","SRC_ACADEMIC_HIST"),
 ("SC2003","Invasión de Irak","2003-03-20","Oriente Medio","IRQ;USA;GBR;IRN;SYR;TUR;SAU",
  "","Superciclo de materias primas en curso","","División transatlántica (Francia/Alemania contra la guerra)","CF034;CF033","","","","","","","","SRC_ACADEMIC_HIST"),
 ("SC2008","Crisis financiera global","2008-09-15","Global","USA;GBR;DEU;FRA;ISL;IRL;ESP;GRC;CHN;RUS;GEO",
  "Fin de la presidencia de Bush; elecciones en EE.UU.","Quiebra de Lehman; precios de materias primas en máximo previo","","Guerra ruso-georgiana (08-2008)","CF036;CF033;CF034","","","","Depresión; crisis de deuda soberana posterior","G20 como foro central","","","SRC_LAEVEN_VALENCIA"),
 ("SC2011","Primavera Árabe","2011-01-25","Norte de África y Oriente Medio","TUN;EGY;LBY;SYR;YEM;BHR;SAU;IRN;TUR",
  "Protestas regionales","Precios de alimentos altos","","","CF038;CF039;CF041","Desempleo juvenil","Autoritarismos longevos","","Guerras civiles","Democratización","","","SRC_ACADEMIC_HIST"),
 ("SC2014","Crimea y el Estado Islámico","2014-03-18","Europa oriental/Oriente Medio","UKR;RUS;IRQ;SYR;USA;DEU;POL",
  "","Caída del precio del petróleo en el segundo semestre","","Sanciones a Rusia; G8 → G7","CF042;CF040;CF038;CF041","","","Euromaidán","","","","","SRC_ACADEMIC_HIST"),
 ("SC2020","Pandemia de COVID-19","2020-03-11","Global","CHN;USA;ITA;ESP;GBR;BRA;IND;DEU",
  "","Contracción mundial (~-3%)","","Tensiones EE.UU.-China","CF045;CF046","Confinamientos","Poderes de emergencia generalizados","","Colapso sanitario; crisis de deuda en emergentes","Vacunas; estímulos","","","SRC_ACADEMIC_HIST"),
 ("SC2022","Invasión de Ucrania","2022-02-24","Europa","UKR;RUS;POL;DEU;FRA;USA;GBR;BLR;FIN;SWE;TUR",
  "","Inflación global, crisis energética","Rusia ~10% del PIB en defensa hacia 2024 (estim.)","Sanciones; ayuda militar occidental","CF043;CF041;CF046","Refugiados (~6 M)","Ley marcial en Ucrania","","Escalada nuclear; guerra prolongada","Rearme europeo; ampliación OTAN","","","SRC_ACADEMIC_HIST"),
 ("SC2024","Superciclo electoral y guerras simultáneas","2024-01-01","Global","USA;IND;IDN;MEX;TWN;RUS;GBR;ZAF;ISR;IRN;UKR",
  "Elecciones en >60 países","Desinflación; tipos altos","","Guerras en Ucrania y Gaza; tensiones en el Estrecho de Taiwán","CF043;CF047;CF048;CF073","","","","Escalada regional en Oriente Medio","","Datos de 2024 parcialmente disponibles","","SRC_ACADEMIC_HIST"),
 ("SC2025","Mundo de 2025","2025-01-20","Global","USA;CHN;RUS;UKR;EUU;IND;ISR;IRN;SYR;BRA;MEX",
  "Segundo mandato de Trump; transición en Siria","Aranceles generalizados de EE.UU.; desaceleración china","Rearme europeo; objetivo OTAN 5%","Erosión del multilateralismo; acercamiento Rusia-Corea del Norte","CF043;CF047;CF048;CF073;CF049","","","Caída de Assad (12-2024)","Guerra comercial; conflicto en Taiwán","","Series 2025 casi inexistentes: los perfiles cuantitativos usan el último año disponible (≤2024) y lo indican","Fecha de corte de la base: datos estadísticos hasta 2024-2025","SRC_ACADEMIC_HIST"),
]
